o = open("nbd3_gen.tex", "w")
o.truncate()
o.write('\\documentclass{amsart}\n') 
o.write('\\usepackage{amsmath,amssymb,amsthm,fullpage,mathptmx, hyperref,dsfont,framed, graphicx, subcaption, textcomp, tikz} % The usual suspects\n') 
o.write('\n') 
o.write('%%%%%%%%%%%%%%%%%% Tikz %%%%%%%%%\n') 
o.write('\\usepackage{tikz}\n') 
o.write('\\usetikzlibrary{shapes.geometric}\n') 
o.write('\\usetikzlibrary{calc}\n') 
o.write('\\usetikzlibrary{scopes}\n') 
o.write('\\usetikzlibrary{decorations.markings}\n') 
o.write('\n') 
o.write('\\tikzset{\n') 
o.write('every picture/.style={line width=0.8pt, >=stealth,\n') 
o.write('                       baseline=-3pt,label distance=-3pt},\n') 
o.write('%%%%%%%%%%  Node styles\n') 
o.write('dotnode/.style={fill=black,circle,minimum size=2.5pt, inner sep=1pt, outer\n') 
o.write('sep=0},\n') 
o.write('morphism/.style={circle,draw,thin, inner sep=1pt, minimum size=15pt,\n') 
o.write('                 scale=0.8},\n') 
o.write('small_morphism/.style={circle,draw,thin,inner sep=1pt,\n') 
o.write('                       minimum size=10pt, scale=0.8},\n') 
o.write('coupon/.style={draw,thin, inner sep=1pt, minimum size=18pt,scale=0.8},\n') 
o.write('%%%% different line styles:\n') 
o.write('regular/.style={densely dashed},\n') 
o.write('edge/.style={thick, dashed, draw=blue, text=black},\n') 
o.write('boundary/.style={thick,  draw=blue, text=black},\n') 
o.write('overline/.style={preaction={draw,line width=2mm,white,-}},\n') 
o.write('drinfeld center/.style={>=stealth,green!60!black, double\n') 
o.write('distance=1pt,text=black},\n') 
o.write('%%%%%%% Fill styles %%%%%%%%%%%%%%%\n') 
o.write('cell/.style={fill=black!10},\n') 
o.write('subgraph/.style={fill=black!30},\n') 
o.write('%%%%%%% Mid-path arrows\n') 
o.write('midarrow/.style={postaction={decorate},\n') 
o.write('                 decoration={\n') 
o.write('                    markings,% switch on markings\n') 
o.write('                    mark=at position #1 with {\\arrow{>}},\n') 
o.write('                 }},\n') 
o.write('midarrow/.default=0.5\n') 
o.write('}\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\\newtheorem{thm}{Theorem}[section]\n') 
o.write('\\newtheorem*{uthm}{Theorem}\n') 
o.write('\\newtheorem{lem}[thm]{Lemma}\n') 
o.write('\\newtheorem*{ulem}{Lemma}\n') 
o.write('\\newtheorem{prop}[thm]{Proposition}\n') 
o.write('%\\newtheorem*{uprop}[thm]{Proposition}\n') 
o.write('\\newtheorem{cor}[thm]{Corollary}\n') 
o.write('\\newtheorem{conj}[thm]{Conjecture}\n') 
o.write('\\newtheorem{defn}[thm]{Definition}\n') 
o.write('\\newtheorem{rmk}[thm]{Remark}\n') 
o.write('\\newtheorem{prob}[thm]{Open problem}\n') 
o.write('\\newtheorem{ques}[thm]{Question}\n') 
o.write('\\newtheorem{fact}[thm]{Fact}\n') 
o.write('\\newtheorem{ex}[thm]{Exercise}\n') 
o.write('\n') 
o.write('\n') 
o.write('\\DeclareMathOperator{\\MCG}{MCG}\n') 
o.write('\\DeclareMathOperator{\\Vect}{Vec}\n') 
o.write('\\DeclareMathOperator{\\Homeo}{Homeo}\n') 
o.write('\\DeclareMathOperator{\\Hom}{Hom}\n') 
o.write('\\DeclareMathOperator{\\Obj}{Obj}\n') 
o.write('\\DeclareMathOperator{\\Irr}{Irr}\n') 
o.write('\\DeclareMathOperator{\\Img}{Im}\n') 
o.write('\n') 
o.write('\\begin{document}\n') 
o.write('\n') 
o.write('\\title{Finiteness for Mapping Class Group Representations from Twisted Dijkgraaf-Witten Theory}\n') 
o.write('\n') 
o.write('\n') 
o.write('\\author{Paul Gustafson}\n') 
o.write('\\email{pgustafs@math.tamu.edu}\n') 
o.write('\\address{Department of Mathematics,\n') 
o.write('    Texas A\\&M University,\n') 
o.write('    College Station, TX\n') 
o.write('    U.S.A.}\n') 
o.write('    \n') 
o.write('\\maketitle\n') 
o.write('\\begin{abstract}\n') 
o.write(' Every twisted Dijkgraaf-Witten representation of a mapping class group of a closed surface has finite image.\n') 
o.write('\\end{abstract}\n') 
o.write('\n') 
o.write('\\section{Introduction}\n') 
o.write('Given a spherical category $\\mathcal A$ over a field $k$ and compact surface $M$, possibly with boundary, the Turaev-Viro construction gives a projective representation of the mapping class group $\\MCG(M)$.  A natural question is to determine the image of these representations.  In particular, when does such a representation have finite image?\n') 
o.write('\n') 
o.write('In this setting, the Property F conjecture \\cite{nr} states that, for a fixed spherical category $\\mathcal A$, all associated mapping class groups are finite if and only if the Drinfeld center $Z(\\mathcal A)$ is weakly integral. \n') 
o.write('\n') 
o.write('%% Do I have to talk about the center at all?  How do dimensions of objects in the center correspond the dimensions in A?\n') 
o.write('\n') 
o.write('The simplest examples of spherical categories are the pointed categories, i.e. categories in which every simple object is invertible.  Every pointed category is equivalent to a category $\\Vect_G^\\omega$, i.e. the category of $G$-graded vector spaces with associativity given by a cocycle $\\omega \\in Z^3(G, k^\\times)$. In this case, the Turaev-Viro construction corresponds with the twisted Dijkgraaf-Witten theory.\n') 
o.write('\n') 
o.write('The center $Z(\\Vect_G^\\omega))$ is equivalent to the category of representations of the twisted quantum double of $G$, which is integral, so the property $F$ conjecture predicts that mapping class group representations from pointed categories should be finite. In this paper, I will verify this in the case where the surface $M$ is closed with an arbitrary finite group $G$ and cocycle $\\omega$.  \n') 
o.write('\n') 
o.write('\\section{Related Work}\n') 
o.write('\n') 
o.write('This is an extension of the result of Fjelstad and Fuchs \\cite{fjfu} showing that, given a surface with at most one boundary component, the mapping class group representations corresponding to the untwisted (i.e. $\\omega = 1$ case) have finite image.  However, the method of proof employed in the current paper is substantially different than theirs.  In their paper, they use an algebraic method of Lyubashenko \\cite{Lyubashenko1996} that gives a projective mapping class group representation to any factorizable ribbon Hopf algebra.  In this paper, I look at the mapping class group action on a vector space of $\\Vect_G^\\omega$-colored embedded graphs defined by Kirillov \\cite{kirillovStringNets}.\n') 
o.write('\n') 
o.write('In \\cite{bantay}, Bantay defined representations of mapping class groups on the Hilbert space of an orbifold model associated to $D^\\omega(G)$.  These representations appear to coincide with the twisted Dijkgraaf-Witten representations. However, the connection is not clear to the current author.  Bantay even mentions that his representations are \\emph{different} than TQFT representations because he treats boundary components differently.  \n') 
o.write('\n') 
o.write('More is known when we fix a particular surface $M$. In the case where $M$ is a torus, it turns out that any Reshitikhin-Turaev representation of the mapping class group of the torus is always finite \\cite{0806.2493}.  In particular, this implies that the Turaev-Viro representations are all finite.  In the case where $M$ is an $n$-punctured disk, the mapping class group of $M$ relative to the boundary of the disk is the braid group $B_n$.  In this case, it has been proved that the Turaev-Viro representations coming from pointed spherical categories are finite \\cite{erw}.\n') 
o.write('\n') 
o.write('\\section{Definitions}\n') 
o.write('\n') 
o.write('Let $M$ be a closed surface of genus $g$.  Let $G$ be finite group, and let $\\Vect_G^\\omega$ denote the category of $G$-graded vector spaces with associativity defined by the normalized 3-cocycle $\\omega \\in Z^3(G, k^\\times)$. \n') 
o.write('\n') 
o.write('Following Kirillov \\cite{kirillovStringNets}, let $H$ be the string-net vector space of $\\Vect_G^\\omega$-colored graph embeddings modulo null graphs. \n') 
o.write('\n') 
o.write('Let $\\Gamma \\in H$. Thinking of $X$ as a quotient of its fundamental polygon, by isotopy we may assume vertices of $\\Gamma$ lie in the interior of the polygon and that all the edges of $\\Gamma$ do not intersect corners and meet the sides transversally.  Evaluating on the interior of the polygon shows that $\\Gamma$ is equivalent to a graph with a single vertex whose edges are simple closed curves, each of which intersect the boundary of the polygon precisely once.  By using the local relations, we can replace all the edges intersecting a side with a single edge labeled by the tensor product of their labels.  If there are no edges intersecting a side, we can insert a single edge labeled by the group identity into $\\Gamma$ that intersects only that side.  Thus, $\\Gamma$ is equivalent to a colored graph with one vertex $v$ and $2n$ outgoing edges $e_1, \\ldots e_{2n}$, each of which intersects precisely one side of the fundamental polygon.\n') 
o.write('\n') 
o.write('\n') 
o.write('%\\begin{figure}\n') 
o.write('%\\begin{tikzpicture}\n') 
o.write('%\\node[ellipse, scale=0.8, inner sep=1pt, draw,thin] (ph) at (3,3) \n') 
o.write('%{$1$};\n') 
o.write('\n') 
o.write('%\\draw (0,0) -- (6,0)  -- (6,6) -- (0,6) -- (0,0);\n') 
o.write('%\\draw (3,0) -- (ph) -- (3,6);\n') 
o.write('%\\draw (0,3) -- (ph) -- (6,3);\n') 
o.write('\n') 
o.write('%\\end{tikzpicture}\n') 
o.write('%\\caption{Element of the spanning set for the torus}\n') 
o.write('%\\end{figure}\n') 
o.write('\n') 
o.write('\n') 
o.write('By the definition of the evaluation of a string-net and the definition of the quotient map identifying the sides of the fundamental polygon, the vertex $v$ is colored by an element $\\phi(v) \\in \\Hom_{\\Vect_G^\\omega} (1, \\bigotimes_{i=1}^n V(e_{2i-1}) \\otimes V(e_{2i})  \\otimes V(e_{2i-1}^*) \\otimes V(e_{2i}^*))$, where $V(e_i) \\in \\Obj(\\Vect_G^\\omega)$ is the coloring of the edge $e_i$.  Since string-net evaluation is additive in the direct sum and linear in the vertex color, it follows that $H$ is spanned by the set of colored graphs\n') 
o.write('$$ S := \\{\\Gamma \\in H : V(e_i) \\in \\Irr(\\Vect_G^\\omega), \\phi(v) = 1 \\}, $$\n') 
o.write('where $\\Irr(\\Vect_G^\\omega)$ is the set of simple objects of $\\Vect_G^\\omega$.  See Figure \\ref{fig:span} for a depiction.\n') 
o.write('\n') 
o.write('\\begin{figure}\n') 
o.write('\\includegraphics[width=0.5\\textwidth]{basis.jpg}\n') 
o.write('\\caption{Element of the spanning set $S$ for a genus 2 surface}\n') 
o.write('\\label{fig:span}\n') 
o.write('\\end{figure}\n') 
o.write('\n') 
o.write('\n') 
o.write('%% The action of the mapping class group on H\n') 
o.write('\n') 
o.write('\\begin{prop}\n') 
o.write('The action of the mapping class group on the vector space $H$ induced by the action of the orientation-preserving homeomorphisms on the surface $M$ is well-defined.\n') 
o.write('\\end{prop}\n') 
o.write('\\begin{proof}\n') 
o.write('The orientation-preserving group $\\Homeo^+(M)$ acts on colored embedded graphs in $M$.  To see that the mapping class group $\\MCG(M)$ has a well-defined action on $H$, we need to check two things: first, that isotopic homeomorphisms acting on a colored graph take it to equivalent colored graphs and, second, that a homeomorphism maps equivalent colored graphs to equivalent colored graphs.\n') 
o.write('\n') 
o.write('For the first, suppose $f, g \\in Homeo^+(M)$ are isotopic, with $H: M \\times I \\to M$ an isotopy from $f$ to $g$.  Let $i: \\Gamma \\to M$ be an graph embedding.  Then $H \\circ i$ is an isotopy from $f \\circ i$ to $g \\circ i$.    \n') 
o.write('\n') 
o.write('For the second,  to check that a homeomorphism $f \\in \\Homeo^+(M)$ preserves equivalence of colored graphs, it suffices to check that it in the case of each local move.  Since the mapping class group is generated by Dehn twists, all the local moves reduce to the isotopy move. \n') 
o.write('\n') 
o.write('To check that isotopic colored graphs get mapped to equivalent colored graphs, suppose $\\Gamma$ is a graph and $i: \\Gamma to M$ and $j: \\Gamma \\to M$ are isotopic embeddings. Let $H: \\Gamma \\times I \\to M$ be an isotopy from $i$ to $j$.  Let $f \\in \\Homeo^+(M)$.  Then $f \\circ H$ is an isotopy from $f \\circ i$ to $f \\circ j$.  \n') 
o.write('\n') 
o.write('Thus, the action of the mapping class group on $H$ is well-defined.\n') 
o.write('\\end{proof}\n') 
o.write('\n') 
o.write('%% The action of H on the spanning set\n') 
o.write('\n') 
o.write('\\begin{thm}\n') 
o.write('The image of the twisted Dijkgraaf-Witten representation of a mapping class group of any closed surface $M$ is finite.\n') 
o.write('\\end{thm}\n') 
o.write('\n') 
o.write('\\begin{proof}\n') 
o.write('The mapping class group of $M$ is generated by the Lickorish generating set consisting of Dehn twists around $3g-1$ simple closed curves (see Figure \\ref{fig:lickorish}).  These can be divided into two types of twists: the ones around a single hole, and the ones connecting two holes.\n') 
o.write('\n') 
o.write('\\begin{figure}\n') 
o.write('\\includegraphics[width=.80\\textwidth]{lickorish.png}\n') 
o.write('\\caption{Lickorish generating set}\n') 
o.write('\\label{fig:lickorish}\n') 
o.write('\\end{figure}\n') 
o.write('\n') 
o.write('\n') 
o.write('\\begin{figure}\n') 
o.write('    \\centering\n') 
o.write('    \\begin{tikzpicture}[scale=5]\n') 
o.write('    \n') 
o.write('    %cut\n') 
o.write('    \\draw[loosely dashed] (0.6, 0.6928) -- (-0.6, 0.6928);\n') 
o.write('    \n') 
o.write('    %boundary of polygon\n') 
o.write('    \\path[draw] (1,0) -- (1/2, 0.866) -- (-1/2, 0.866) -- (-1, 0);\n') 
o.write('\n') 
o.write('    %graph edges\n') 
o.write('    \\begin{scope}[very thick,decoration={\n') 
o.write('    markings,\n') 
o.write('    mark=at position 0.5 with {\\arrow{>}}}\n') 
o.write('    ]  \n') 
o.write('        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0.75, 0.433) node[pos=.5,sloped,above]{$h$};\n') 
o.write('        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0, 0.866) node[pos=.5,left]{$g$};\n') 
o.write('        \\draw[postaction={decorate}]  (-0.75, 0.433) -- (0, 0.2) node[pos=.5,sloped,above]{$h$};\n') 
o.write('        \\draw[postaction={decorate}]  (0, 0.2) -- (0, 0) node[pos=.5,left]{$hg^{-1}h$};\n') 
o.write('        \\draw (0, 0.2) -- (0.1, 0.3);\n') 
o.write('    \\end{scope}\n') 
o.write('    \\end{tikzpicture}\n') 
o.write('    \\caption{First type of Dehn twist}\n') 
o.write('    \\label{fig:tikzTwist1_1}\n') 
o.write('\\end{figure}\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\\begin{figure}\n') 
o.write('    \\centering\n') 
o.write('    \\begin{tikzpicture}[scale=5]\n') 
o.write('    \n') 
o.write('    %boundary of polygon\n') 
o.write('    \\path[draw] (1,0) -- (1/2, 0.866) -- (-1/2, 0.866) -- (-1, 0);\n') 
o.write('\n') 
o.write('    %graph edges\n') 
o.write('    \\begin{scope}[very thick,decoration={\n') 
o.write('    markings,\n') 
o.write('    mark=at position 0.5 with {\\arrow{>}}}\n') 
o.write('    ] \n') 
o.write('\n') 
o.write('\n') 
o.write('        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0.75, 0.433) node[pos=.5,sloped,above]{$h$};\n') 
o.write('        % old g\n') 
o.write('        % \\draw[postaction={decorate}]  (0.1, 0.3) -- (0, 0.866) node[pos=.5,left]{$g$};\n') 
o.write('        \\draw[postaction={decorate}]  (-0.75, 0.433) -- (0, 0.2) node[pos=.5,sloped,above]{$h$};\n') 
o.write('        \\draw[postaction={decorate}]  (0, 0.2) -- (0, 0) node[pos=.5,left]{$hg^{-1}h$};\n') 
o.write('        \\draw (0, 0.2) -- (0.1, 0.3);\n') 
o.write('\n') 
o.write('        % new g\n') 
o.write('        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0.6, 0.6928)\n') 
o.write('        node[pos=.5,sloped,above]{$g$};\n') 
o.write('        \\draw[postaction={decorate}]  (-0.6, 0.6928) -- (0, 0.866)\n') 
o.write('        node[pos=.5,sloped,below]{$g$};\n') 
o.write('\n') 
o.write('    \\end{scope}\n') 
o.write('    \\end{tikzpicture}\n') 
o.write('    \\caption{First type of Dehn twist}\n') 
o.write('    \\label{fig:tikzTwist1_3}\n') 
o.write('\\end{figure}\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\\begin{figure}\n') 
o.write('    \\centering\n') 
o.write('    \\begin{tikzpicture}[scale=5]\n') 
o.write('    \n') 
o.write('    %boundary of polygon\n') 
o.write('    \\path[draw] (1,0) -- (1/2, 0.866) -- (-1/2, 0.866) -- (-1, 0);\n') 
o.write('\n') 
o.write('    %graph edges\n') 
o.write('    \\begin{scope}[very thick,decoration={\n') 
o.write('    markings,\n') 
o.write('    mark=at position 0.5 with {\\arrow{>}}}\n') 
o.write('    ] \n') 
o.write('\n') 
o.write('        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0.75, 0.433) node[pos=.5,sloped,above]{$h$};\n') 
o.write('        % old g\n') 
o.write('        % \\draw[postaction={decorate}]  (0.1, 0.3) -- (0, 0.866) node[pos=.5,left]{$g$};\n') 
o.write('        \\draw[postaction={decorate}]  (-0.75, 0.433) -- (0, 0.2) node[pos=.5,sloped,above]{$h$};\n') 
o.write('        \\draw[postaction={decorate}]  (0, 0.2) -- (0, 0) node[pos=.5,left]{$hg^{-1}h$};\n') 
o.write('        \\draw (0, 0.2) -- (0.1, 0.3);\n') 
o.write('\n') 
o.write('        % new g\n') 
o.write('        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0.6, 0.6928)\n') 
o.write('        node[pos=.5,sloped,above]{$g$};\n') 
o.write('        \\draw[postaction={decorate}]  (-0.6, 0.6928) -- (0, 0.866)\n') 
o.write('        node[pos=.5,sloped,below]{$g$};\n') 
o.write('\n') 
o.write('        \\draw (-0.15, 0.8227) -- (0.05, 0.25);\n') 
o.write('\n') 
o.write('    \\end{scope}\n') 
o.write('    \\end{tikzpicture}\n') 
o.write('    \\caption{First type of Dehn twist}\n') 
o.write('    \\label{fig:tikzTwist1_3}\n') 
o.write('\\end{figure}\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('%% %% Type 1 twist (easy)\n') 
o.write('%% \\begin{figure}[htb]\n') 
o.write('%% \\centering\n') 
o.write('%%   \\begin{tabular}{@{}cc@{}}\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{1.jpeg} &\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{2.jpeg} \\\\\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{3.jpeg} &\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{4.jpeg} \\\\\n') 
o.write('%%   \\end{tabular}\n') 
o.write('%%   \\caption{First type of Dehn twist}\n') 
o.write('%%   \\label{fig:dehn1}\n') 
o.write('%% \\end{figure}\n') 
o.write('\n') 
o.write('\n') 
o.write('%% %% Type 2 twist (harder)\n') 
o.write('%% \\begin{figure}[htb]\n') 
o.write('%% \\centering\n') 
o.write('%%   \\begin{tabular}{@{}cc@{}}\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{5.jpeg} &\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{7.jpeg} \\\\\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{8.jpeg} &\n') 
o.write('%%     \\includegraphics[width=.48\\textwidth]{9.jpeg} \\\\\n') 
o.write('%%   \\end{tabular}\n') 
o.write('%%   \\caption{Second type of Dehn twist}\n') 
o.write('%%   \\label{fig:dehn2}\n') 
o.write('%% \\end{figure}\n') 
o.write('\n') 
o.write(' Using the local moves as in Figures \\ref{fig:dehn1} and \\ref{fig:dehn2}, one sees that the result of each of these Dehn twists lies in $\\Img(\\omega) S$.  It is a basic result in group cohomology that, by replacing $\\omega$ with a cohomologous cocycle if necessary, $\\Img(\\omega) \\subset \\mu_{|G|}$, where $\\mu_{|G|} \\subset k^\\times$ is the finite set of $|G|$-th roots of unity.  \n') 
o.write('\n') 
o.write('Thus, the image of any such mapping class group representation is finite.\n') 
o.write('\\end{proof}\n') 
o.write('\n') 
o.write('\\medskip\n') 
o.write(' \n') 
o.write('\\bibliographystyle{unsrt}\n') 
o.write('\\bibliography{stringnets}\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\n') 
o.write('\\end{document}\n') 
o.close()
