print '\\begin{figure}' 
print '    \\centering' 
print '    \\begin{tikzpicture}[scale=5]' 
print '    ' 
print '    %boundary of polygon' 
print '    \\path[draw] (1,0) -- (1/2, 0.866) -- (-1/2, 0.866) -- (-1, 0);' 
print '' 
print '    %graph edges' 
print '    \\begin{scope}[very thick,decoration={' 
print '    markings,' 
print '    mark=at position 0.5 with {\\arrow{>}}}' 
print '    ] ' 
print '' 
print '        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0.75, 0.433) node[pos=.5,sloped,above]{$h$};' 
print '        % old g' 
print '        % \\draw[postaction={decorate}]  (0.1, 0.3) -- (0, 0.866) node[pos=.5,left]{$g$};' 
print '        \\draw[postaction={decorate}]  (-0.75, 0.433) -- (0, 0.2) node[pos=.5,sloped,above]{$h$};' 
print '        \\draw[postaction={decorate}]  (0, 0.2) -- (0, 0) node[pos=.5,left]{$hg^{-1}h$};' 
print '        \\draw (0, 0.2) -- (0.1, 0.3);' 
print '' 
print '        % new g' 
print '        \\draw[postaction={decorate}]  (0.1, 0.3) -- (0.6, 0.6928)' 
print '        node[pos=.5,sloped,above]{$g$};' 
print '        \\draw[postaction={decorate}]  (-0.6, 0.6928) -- (0, 0.866)' 
print '        node[pos=.5,sloped,below]{$g$};' 
print '' 
print '        \\draw (-0.15, 0.8227) -- (0.05, 0.25);' 
print '' 
print '    \\end{scope}' 
print '    \\end{tikzpicture}' 
print '    \\caption{First type of Dehn twist}' 
print '    \\label{fig:tikzTwist1_3}' 
print '\\end{figure}' 
print '' 
print '' 
